version: '3.7'

services:
      redis:
        image: 'redis:latest'
        container_name: 'chat-py-redis'
        expose:
          - "6379"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
    #     - HOST_REDIS=yes
    #     - PORT_REDIS=6379

    # server:
    #   image: 'chat-py'
    #   container_name: 'chat-py-server'


    # client:
    #   image: 'chat-py'
    #   container_name: 'chat-py-client'

